id: e9d8985a-7ff0-450a-b037-0eed63a5a55f
name: aws-qldb
description: |-
  ## What is AWS QLDB?

  Create a cryptographically verifiable ledger database that's managed by one
  group.


  ### Get started!

  Start monitoring AWS QLDB by connecting Amazon Web Services (AWS) to New Relic!

  Check out our AWS QLDB documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info

  New Relic offers an integration for reporting your Amazon Quantum Ledger Database (QLDB) data to New Relic. [This documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-qldb-monitoring-integration/) explains how to activate this integration and describes the data that can be reported.

summary: |-
  Monitor AWS QLDB by connecting AWS to New Relic
logo: logo.svg
level: New Relic
authors:
  - New Relic
  - Emil Hammarstrand
title: AWS QLDB
documentation:
  - name: AWS QLDB installation docs
    description: |
      Monitor AWS QLDB by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-qldb-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - database

installPlans:
  - aws-infrastructure-monitoring
